<a href="https://colab.research.google.com/github/YungJammy105/Python/blob/master/Homework10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 44:

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head()

  whoAmI
0  robot
1  human
2  human
3  robot
4  human

In [3]:
pd.get_dummies(data['whoAmI'])

    human  robot
0       0      1
1       1      0
2       1      0
3       0      1
4       1      0
5       1      0
6       0      1
7       1      0
8       0      1
9       1      0
10      1      0
11      1      0
12      0      1
13      0      1
14      0      1
15      0      1
16      1      0
17      0      1
18      1      0
19      0      1

In [4]:
encode = {"whoAmI": {"human": 1, "robot": 0}}
data = data.replace(encode)

In [5]:
data

    whoAmI
0        0
1        1
2        1
3        0
4        1
5        1
6        0
7        1
8        0
9        1
10       1
11       1
12       0
13       0
14       0
15       0
16       1
17       0
18       1
19       0